export const GET_CUSTOMERS_START = 'GET_CUSTOMERS_START';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAIL = 'GET_CUSTOMERS_FAIL';

export const ADD_CUSTOMER_START = 'ADD_CUSTOMER_START';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAIL = 'ADD_CUSTOMER_FAIL';

export const EDIT_CUSTOMER_START = 'EDIT_CUSTOMER_START';
export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_FAIL = 'EDIT_CUSTOMER_FAIL';

export const DELETE_CUSTOMER_START = 'DELETE_CUSTOMER_START';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL';

export const GET_CUSTOMER_WEATHER_FORECAST =  'GET_CUSTOMER_WEATHER_FORECAST';