version: '3.7'

services:
  web:
    image: node
    container_name: fake_umbrella_web
    working_dir: /app
    volumes:
      - ./fakeumbrella:/app
    ports:
      - 80:3000
    stdin_open: true
    command: bash

networks:
  default:
    external:
      name: zed